var examples={brand:'나의 위키',title:'위키 문서 제목',subtitle:'문서를 한 줄로 설명하는 부제목',tocTitle:'목차',infoName:'대표 정보',caption:'이미지에 대한 설명을 입력하세요.'};
var infoRowExamples=[{label:'분류',value:'인물 · 창작 · 설정'},{label:'출처',value:'개인 아카이브'},{label:'태그',value:'#위키 #기록 #아카이브'}];
var sectionExamples=[{title:'개요',body:'문서의 첫 번째 본문입니다. 인물이나 작품, 세계관에 대한 핵심 설명을 자유롭게 작성하세요.\nShift + Enter로 문단을 나눌 수 있습니다.'},{title:'상세',body:'두 번째 본문에는 세부 설정, 관계, 타임라인이나 감상 등을 정리할 수 있습니다.'}];
var fontFamilies={pretendard:'"Pretendard", sans-serif',noto:'"Noto Sans KR", sans-serif',ridi:'"RIDIBatang", serif',galmuri:'"Galmuri14", "Galmuri11", monospace'};
var defaults={accent:'#00a495',text:'#202529',paper:'#ffffff',font:'pretendard',brand:'',title:'',subtitle:'',tocTitle:'',infoName:'',infoRows:[{label:'',value:''},{label:'',value:''},{label:'',value:''}],sections:[{toc:'',title:'',body:'',quotes:[]},{toc:'',title:'',body:'',quotes:[]}],profileImage:'',bodyImages:[],profileCrop:{zoom:100,x:50,y:50}};
function clone(value){return JSON.parse(JSON.stringify(value))}
var saved={};try{saved=JSON.parse(localStorage.getItem('wiki-frame-v1')||'{}')}catch(error){}
var state=Object.assign(clone(defaults),saved);
if(!Array.isArray(saved.infoRows)){state.infoRows=[{label:'분류',value:String(saved.category||'')},{label:'출처',value:String(saved.source||'')},{label:'태그',value:String(saved.tags||'')}]}
if(!Array.isArray(saved.bodyImages)){state.bodyImages=saved.bodyImage?[{source:String(saved.bodyImage),caption:String(saved.caption||''),crop:Object.assign({zoom:100,x:50,y:50},saved.bodyCrop||{})}]:[]}
if(!Array.isArray(saved.sections)){state.sections=[{toc:'',title:String(saved.sectionOneTitle||''),body:String(saved.sectionOneBody||''),quotes:[]},{toc:'',title:String(saved.sectionTwoTitle||''),body:String(saved.sectionTwoBody||''),quotes:[]}]}
state.infoRows=state.infoRows.filter(function(item){return item&&typeof item==='object'}).map(function(item){return{label:String(item.label||''),value:String(item.value||'')}});if(!state.infoRows.length)state.infoRows=[{label:'',value:''}];
state.bodyImages=state.bodyImages.filter(function(item){return item&&typeof item==='object'&&item.source}).map(function(item){return{source:String(item.source),caption:String(item.caption||''),crop:Object.assign({zoom:100,x:50,y:50},item.crop||{})}});
state.sections=state.sections.filter(function(item){return item&&typeof item==='object'}).map(function(item){return{toc:String(item.toc||''),title:String(item.title||''),body:String(item.body||''),quotes:Array.isArray(item.quotes)?item.quotes.map(function(quote){return typeof quote==='object'&&quote!==null?{text:String(quote.text||''),position:quote.position==='before'?'before':'after'}:{text:String(quote||''),position:'after'}}):[]}});if(!state.sections.length)state.sections=[{toc:'',title:'',body:'',quotes:[]}];
state.sections.forEach(function(section){if(!section.title.trim()&&section.toc.trim())section.title=section.toc;section.toc=section.title});
state.profileCrop=Object.assign({zoom:100,x:50,y:50},state.profileCrop||{});
var exporting=false,activeImage=null,sheet=document.getElementById('wikiSheet'),frame=document.querySelector('.sheet-frame');
var textKeys=['brand','title','subtitle','tocTitle','infoName'];
var inputMap={brand:'brandInput',title:'titleInput',subtitle:'subtitleInput',tocTitle:'tocTitleInput',infoName:'infoNameInput'};
var viewMap={title:'titleView',subtitle:'subtitleView',tocTitle:'tocTitleView',infoName:'infoNameView'};
function valueOf(key){var value=String(state[key]||'');return value.trim()?value:(exporting?'':examples[key]||'')}
function sectionValue(section,key,index){var value=String(section[key]||'');if(value.trim())return value;if(exporting)return'';var sample=sectionExamples[index];return sample?sample[key]:(key==='title'?'새 항목':'항목 내용을 입력하세요.')}
function save(){try{localStorage.setItem('wiki-frame-v1',JSON.stringify(state))}catch(error){}}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function fitFrame(){requestAnimationFrame(function(){frame.style.height=Math.ceil(sheet.getBoundingClientRect().height)+'px'})}
function fitLine(field){if(!field||!field.classList.contains('line'))return;field.style.height='auto';field.style.height=Math.max(37,field.scrollHeight)+'px'}
function imageFile(input,done){var file=input.files&&input.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){done(String(reader.result))};reader.readAsDataURL(file)}
function imageFiles(input,done){var files=Array.from(input.files||[]);if(!files.length)return;Promise.all(files.map(function(file){return new Promise(function(resolve){var reader=new FileReader();reader.onload=function(){resolve(String(reader.result))};reader.readAsDataURL(file)})})).then(done)}
function imageData(slot){if(slot==='profile')return state.profileImage?{slot:'profile',source:state.profileImage,crop:state.profileCrop,box:document.querySelector('[data-image-slot="profile"]'),label:'대표 이미지'}:null;if(!String(slot).startsWith('body-'))return null;var index=Number(String(slot).slice(5)),item=state.bodyImages[index];return item?{slot:slot,source:item.source,crop:item.crop,box:document.querySelector('[data-image-slot="'+slot+'"]'),label:'본문 이미지 '+(index+1)}:null}
function layoutImage(image,crop){if(!image||!image.naturalWidth)return;var box=image.parentElement,bw=box.clientWidth,bh=box.clientHeight,x=Number(crop.x),y=Number(crop.y),zoom=Math.max(1,Number(crop.zoom||100)/100);if(!Number.isFinite(x))x=50;if(!Number.isFinite(y))y=50;var cover=Math.max(bw/image.naturalWidth,bh/image.naturalHeight),width=image.naturalWidth*cover*zoom,height=image.naturalHeight*cover*zoom;image.style.width=width+'px';image.style.height=height+'px';image.style.left=(-(width-bw)*clamp(x,0,100)/100)+'px';image.style.top=(-(height-bh)*clamp(y,0,100)/100)+'px'}
function mountImage(data){if(!data||!data.box)return;var image=document.createElement('img');image.className='native-image';image.alt='';image.src=data.source;image._cropData=data.crop;data.box.querySelector('span').style.display='none';data.box.appendChild(image);if(image.complete)layoutImage(image,data.crop);else image.onload=function(){layoutImage(image,data.crop);fitFrame()};setupImage(data,image);if(activeImage===data.slot)image.classList.add('active-image')}
function setupImage(data,image){image.tabIndex=0;image.setAttribute('role','button');image.setAttribute('aria-label',data.label+' 위치 조정');image.onpointerdown=function(event){if(event.button!==0)return;event.preventDefault();selectImage(data.slot);var rect=data.box.getBoundingClientRect(),startX=event.clientX,startY=event.clientY,start={x:Number(data.crop.x),y:Number(data.crop.y)};image.setPointerCapture&&image.setPointerCapture(event.pointerId);function move(e){data.crop.x=clamp(start.x-(e.clientX-startX)/rect.width*100,0,100);data.crop.y=clamp(start.y-(e.clientY-startY)/rect.height*100,0,100);layoutImage(image,data.crop)}function stop(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);save()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)};image.onwheel=function(event){event.preventDefault();selectImage(data.slot);data.crop.zoom=clamp(Number(data.crop.zoom)+(event.deltaY<0?5:-5),100,250);layoutImage(image,data.crop);save()};image.onclick=function(){selectImage(data.slot)}}
function selectImage(slot){document.querySelectorAll('.active-image').forEach(function(el){el.classList.remove('active-image')});var data=imageData(slot);if(!data||!data.box)return;activeImage=slot;var image=data.box.querySelector('img');if(image)image.classList.add('active-image');document.getElementById('imageStatus').textContent=data.label+' 선택됨 · '+data.crop.zoom+'% · 드래그 이동 · 휠 확대/축소 · 방향키 미세조정'}
function makeBodyFigure(index){var item=index===null?null:state.bodyImages[index],figure=document.createElement('figure'),slot=document.createElement('div'),placeholder=document.createElement('span'),caption=document.createElement('figcaption');slot.className='image-slot body-slot';slot.dataset.imageSlot=item?'body-'+index:'body-placeholder';placeholder.textContent=item?'본문 이미지 '+(index+1):'본문 이미지';slot.appendChild(placeholder);caption.textContent=item?(String(item.caption||'').trim()?item.caption:(exporting?'':examples.caption)):examples.caption;figure.appendChild(slot);if(!exporting||String(caption.textContent).trim())figure.appendChild(caption);return figure}
function escapeHtml(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function richHTML(value){var raw=String(value||'');return raw?(raw.indexOf('<')!==-1?raw:escapeHtml(raw).replace(/\n/g,'<br>')):''}
function hasRichText(value){return String(value||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim().length>0}
function makeQuote(quote){var citation=document.createElement('blockquote'),text=String(quote.text||'');citation.className='document-quote';citation.innerHTML=hasRichText(text)?richHTML(text):(exporting?'':'인용할 대사를 입력하세요.');return citation}
function renderSections(){var toc=document.getElementById('tocList'),list=document.getElementById('sectionList');toc.replaceChildren();list.replaceChildren();state.sections.forEach(function(section,index){var number=index+1,id='section-'+number,li=document.createElement('li'),num=document.createElement('span'),link=document.createElement('a');num.textContent=number+'.';link.href='#'+id;link.textContent=sectionValue(section,'title',index);li.appendChild(num);li.appendChild(link);toc.appendChild(li);var block=document.createElement('section'),heading=document.createElement('h2'),headingNum=document.createElement('span'),headingText=document.createElement('b'),body=document.createElement('p');block.className='document-section';block.id=id;headingNum.textContent=number+'.';headingText.textContent=sectionValue(section,'title',index);body.className='rich-content';body.innerHTML=richHTML(sectionValue(section,'body',index));heading.appendChild(headingNum);heading.appendChild(headingText);block.appendChild(heading);if(index===0){if(state.bodyImages.length){var grid=document.createElement('div');grid.className='body-image-grid';state.bodyImages.forEach(function(item,imageIndex){grid.appendChild(makeBodyFigure(imageIndex))});block.appendChild(grid)}else if(!exporting)block.appendChild(makeBodyFigure(null))}section.quotes.filter(function(quote){return quote.position==='before'}).forEach(function(quote){if(!exporting||hasRichText(quote.text))block.appendChild(makeQuote(quote))});block.appendChild(body);section.quotes.filter(function(quote){return quote.position!=='before'}).forEach(function(quote){if(!exporting||hasRichText(quote.text))block.appendChild(makeQuote(quote))});list.appendChild(block)})}
function infoValue(row,key,index){var value=String(row[key]||'');if(value.trim())return value;if(exporting)return'';var sample=infoRowExamples[index];return sample?sample[key]:(key==='label'?'항목':'내용을 입력하세요.')}
function renderInfoRows(){var list=document.getElementById('infoRowsList');list.replaceChildren();state.infoRows.forEach(function(row,index){if(exporting&&!String(row.label||'').trim()&&!String(row.value||'').trim())return;var item=document.createElement('div'),term=document.createElement('dt'),description=document.createElement('dd');term.textContent=infoValue(row,'label',index);description.textContent=infoValue(row,'value',index);item.appendChild(term);item.appendChild(description);list.appendChild(item)})}
function render(){sheet.style.setProperty('--accent',state.accent);sheet.style.setProperty('--text',state.text);sheet.style.setProperty('--paper',state.paper);sheet.style.fontFamily=fontFamilies[state.font]||fontFamilies.pretendard;document.querySelectorAll('[data-brand]').forEach(function(el){el.textContent=valueOf('brand')});Object.keys(viewMap).forEach(function(key){document.getElementById(viewMap[key]).textContent=valueOf(key)});renderInfoRows();renderSections();document.querySelectorAll('.image-slot img').forEach(function(image){image.remove()});document.querySelectorAll('.image-slot>span').forEach(function(span){span.style.display='grid'});var profileSlot=document.querySelector('[data-image-slot="profile"]');if(profileSlot)profileSlot.classList.toggle('empty-image-slot',!state.profileImage);mountImage(imageData('profile'));state.bodyImages.forEach(function(item,index){mountImage(imageData('body-'+index))});fitFrame()}
function sectionField(labelText,value,placeholder,className,rows,onInput){var label=document.createElement('label'),field=document.createElement('textarea');label.appendChild(document.createTextNode(labelText));field.value=value;field.placeholder=placeholder;field.rows=rows;if(className)field.className=className;field.oninput=function(){onInput(field.value);fitLine(field);save();render()};label.appendChild(field);requestAnimationFrame(function(){fitLine(field)});return label}
function richTextField(labelText,value,placeholder,onInput){var wrap=document.createElement('div'),caption=document.createElement('span'),toolbar=document.createElement('div'),editor=document.createElement('div'),color=document.createElement('input'),savedRange=null;wrap.className='rich-field';caption.textContent=labelText;toolbar.className='rich-toolbar';editor.className='rich-editor';editor.contentEditable='true';editor.setAttribute('role','textbox');editor.setAttribute('aria-multiline','true');editor.dataset.placeholder=placeholder;editor.innerHTML=richHTML(value);function remember(){var selection=window.getSelection();if(selection&&selection.rangeCount&&editor.contains(selection.anchorNode))savedRange=selection.getRangeAt(0).cloneRange()}function restore(){if(!savedRange)return;var selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedRange)}function commit(){onInput(editor.innerHTML);save();render()}[['B','bold','굵게'],['I','italic','기울임'],['S','strikeThrough','취소선']].forEach(function(spec){var button=document.createElement('button');button.type='button';button.textContent=spec[0];button.title=spec[2];button.setAttribute('aria-label',spec[2]);button.onmousedown=function(event){event.preventDefault();restore();document.execCommand(spec[1],false,null);remember();commit()};toolbar.appendChild(button)});color.type='color';color.value='#e03131';color.title='글자색';color.setAttribute('aria-label','글자색');color.oninput=function(){restore();document.execCommand('foreColor',false,color.value);remember();commit()};toolbar.appendChild(color);editor.oninput=function(){remember();commit()};editor.onkeyup=remember;editor.onmouseup=remember;editor.onfocus=remember;wrap.appendChild(caption);wrap.appendChild(toolbar);wrap.appendChild(editor);return wrap}
function buildQuoteEditors(card,section,index){var label=document.createElement('span'),list=document.createElement('div'),add=document.createElement('button');label.className='quote-editor-label';label.textContent='대사 인용구';list.className='quote-editor-list';function refresh(){list.replaceChildren();section.quotes.forEach(function(quote,quoteIndex){var row=document.createElement('div'),position=document.createElement('select'),remove=document.createElement('button'),field;row.className='quote-editor-row';position.className='quote-position';position.innerHTML='<option value="before">본문 위</option><option value="after">본문 아래</option>';position.value=quote.position;position.onchange=function(){quote.position=position.value;save();render()};remove.type='button';remove.className='quote-remove';remove.textContent='삭제';remove.onclick=function(){section.quotes.splice(quoteIndex,1);save();refresh();render()};field=richTextField('인용문 '+String(quoteIndex+1),quote.text,'인용할 대사를 입력하세요.',function(value){quote.text=value});field.querySelector('.rich-toolbar').appendChild(position);field.querySelector('.rich-toolbar').appendChild(remove);row.appendChild(field);list.appendChild(row)})}add.type='button';add.className='add-quote';add.textContent='＋ 대사 인용구 추가';add.onclick=function(){section.quotes.push({text:'',position:'after'});save();refresh();render()};card.appendChild(label);card.appendChild(list);card.appendChild(add);refresh()}
function appendSectionFields(card,section,index){var sample=sectionExamples[index]||{title:'새 항목',body:'항목 내용을 입력하세요.'};card.appendChild(sectionField('본문 제목 · 목차 항목',section.title,sample.title,'line',1,function(value){section.title=value;section.toc=value}));card.appendChild(richTextField('항목 내용',section.body,sample.body,function(value){section.body=value}));buildQuoteEditors(card,section,index)}
function buildOverviewEditor(){var list=document.getElementById('overviewEditor'),section=state.sections[0],card=document.createElement('div'),head=document.createElement('div'),title=document.createElement('strong');list.replaceChildren();card.className='section-editor-card';head.className='section-editor-head';title.textContent='개요 내용';head.appendChild(title);card.appendChild(head);appendSectionFields(card,section,0);list.appendChild(card)}
function buildSectionEditors(){var list=document.getElementById('sectionEditorList');list.replaceChildren();state.sections.slice(1).forEach(function(section,offset){var index=offset+1,card=document.createElement('div'),head=document.createElement('div'),title=document.createElement('strong'),remove=document.createElement('button');card.className='section-editor-card';head.className='section-editor-head';title.textContent='본문 항목 '+String(index).padStart(2,'0');remove.type='button';remove.textContent='삭제';remove.onclick=function(){state.sections.splice(index,1);save();buildSectionEditors();render()};head.appendChild(title);head.appendChild(remove);card.appendChild(head);appendSectionFields(card,section,index);list.appendChild(card)})}
function buildInfoRowEditors(){var list=document.getElementById('infoRowEditorList');list.replaceChildren();state.infoRows.forEach(function(row,index){var card=document.createElement('div'),head=document.createElement('div'),title=document.createElement('strong'),remove=document.createElement('button'),sample=infoRowExamples[index]||{label:'항목',value:'내용을 입력하세요.'};card.className='section-editor-card info-row-card';head.className='section-editor-head';title.textContent='대표 정보 '+String(index+1).padStart(2,'0');remove.type='button';remove.textContent='삭제';remove.disabled=state.infoRows.length===1;remove.onclick=function(){state.infoRows.splice(index,1);save();buildInfoRowEditors();render()};head.appendChild(title);head.appendChild(remove);card.appendChild(head);card.appendChild(sectionField('항목 이름',row.label,sample.label,'line',1,function(value){row.label=value}));card.appendChild(sectionField('항목 내용',row.value,sample.value,'line',1,function(value){row.value=value}));list.appendChild(card)})}
function buildBodyImageEditors(){var list=document.getElementById('bodyImageEditorList');list.replaceChildren();state.bodyImages.forEach(function(item,index){var card=document.createElement('div'),head=document.createElement('div'),title=document.createElement('strong'),remove=document.createElement('button');card.className='section-editor-card body-image-card';head.className='section-editor-head';title.textContent='본문 이미지 '+String(index+1).padStart(2,'0');remove.type='button';remove.textContent='삭제';remove.onclick=function(){state.bodyImages.splice(index,1);activeImage=null;save();buildBodyImageEditors();render()};head.appendChild(title);head.appendChild(remove);card.appendChild(head);card.appendChild(sectionField('이미지 설명',item.caption,examples.caption,'line',1,function(value){item.caption=value}));list.appendChild(card)})}
textKeys.forEach(function(key){var field=document.getElementById(inputMap[key]);field.value=state[key];field.placeholder=examples[key]||'';fitLine(field);field.oninput=function(){state[key]=field.value;fitLine(field);save();render()}});
document.getElementById('accentInput').value=state.accent;document.getElementById('textInput').value=state.text;document.getElementById('paperInput').value=state.paper;document.getElementById('fontInput').value=state.font;
document.getElementById('accentInput').oninput=function(){state.accent=this.value;save();render()};document.getElementById('textInput').oninput=function(){state.text=this.value;save();render()};document.getElementById('paperInput').oninput=function(){state.paper=this.value;save();render()};document.getElementById('fontInput').onchange=function(){state.font=this.value;save();render()};
document.getElementById('addSectionButton').onclick=function(){state.sections.push({toc:'',title:'',body:'',quotes:[]});save();buildOverviewEditor();buildSectionEditors();render()};document.getElementById('profileUpload').onchange=function(){imageFile(this,function(value){state.profileImage=value;save();render();selectImage('profile')})};document.getElementById('bodyUpload').onchange=function(){var input=this;imageFiles(input,function(values){var start=state.bodyImages.length;values.forEach(function(value){state.bodyImages.push({source:value,caption:'',crop:{zoom:100,x:50,y:50}})});input.value='';save();buildBodyImageEditors();render();selectImage('body-'+start)})};
document.getElementById('addInfoRowButton').onclick=function(){state.infoRows.push({label:'',value:''});save();buildInfoRowEditors();render()};
document.addEventListener('keydown',function(event){if(event.key==='Enter'&&event.shiftKey&&event.target.tagName==='TEXTAREA'){event.preventDefault();event.target.setRangeText('\n',event.target.selectionStart,event.target.selectionEnd,'end');event.target.dispatchEvent(new Event('input',{bubbles:true}));return}if(!activeImage||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)||event.target.closest('input,textarea,button,select'))return;var data=imageData(activeImage),step=event.shiftKey?5:1;if(!data)return;event.preventDefault();if(event.key==='ArrowLeft')data.crop.x=clamp(data.crop.x+step,0,100);if(event.key==='ArrowRight')data.crop.x=clamp(data.crop.x-step,0,100);if(event.key==='ArrowUp')data.crop.y=clamp(data.crop.y+step,0,100);if(event.key==='ArrowDown')data.crop.y=clamp(data.crop.y-step,0,100);layoutImage(data.box.querySelector('img'),data.crop);save()});
document.getElementById('resetButton').onclick=function(){if(!confirm('입력한 내용과 이미지를 모두 초기화할까요?'))return;localStorage.removeItem('wiki-frame-v1');state=clone(defaults);activeImage=null;textKeys.forEach(function(key){document.getElementById(inputMap[key]).value=''});document.getElementById('accentInput').value=state.accent;document.getElementById('textInput').value=state.text;document.getElementById('paperInput').value=state.paper;document.getElementById('fontInput').value=state.font;buildInfoRowEditors();buildBodyImageEditors();buildOverviewEditor();buildSectionEditors();render()};
document.getElementById('saveButton').onclick=async function(){if(!window.html2canvas)return alert('저장 기능을 불러오는 중입니다.');var button=this;button.disabled=true;button.textContent='저장 중…';exporting=true;document.body.classList.add('saving');render();try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;await Promise.all(Array.from(sheet.querySelectorAll('img.native-image')).map(function(image){return image.decode?image.decode().catch(function(){}):Promise.resolve()}));sheet.querySelectorAll('img.native-image').forEach(function(image){layoutImage(image,image._cropData)});await new Promise(function(resolve){requestAnimationFrame(function(){requestAnimationFrame(resolve)})});var area=sheet.scrollWidth*sheet.scrollHeight,scale=Math.max(2,Math.min(4,Math.sqrt(45000000/Math.max(1,area)))),canvas=await window.html2canvas(sheet,{scale:scale,backgroundColor:state.paper,useCORS:true,logging:false,imageTimeout:30000}),link=document.createElement('a');link.download='wiki-'+(state.title||'document')+'.png';link.href=canvas.toDataURL('image/png');link.click()}catch(error){alert('PNG를 만들지 못했습니다. 이미지 용량을 줄여 다시 시도해주세요.')}finally{exporting=false;document.body.classList.remove('saving');button.disabled=false;button.textContent='PNG 저장';render()}};
var panel=document.getElementById('editorPanel'),toggle=document.getElementById('mobileToggle'),closeButton=document.getElementById('mobileClose'),backdrop=document.getElementById('editorBackdrop');function setEditor(open){document.body.classList.toggle('editor-open',open);panel.classList.toggle('open',open);backdrop.classList.toggle('show',open);toggle.setAttribute('aria-expanded',String(open))}toggle.onclick=function(){setEditor(true)};closeButton.onclick=function(){setEditor(false)};backdrop.onclick=function(){setEditor(false)};window.addEventListener('resize',fitFrame);buildInfoRowEditors();buildBodyImageEditors();buildOverviewEditor();buildSectionEditors();render();

