var examples={brand:'나의 위키',title:'위키 문서 제목',subtitle:'문서를 한 줄로 설명하는 부제목',summary:'이 문서는 사용자가 직접 편집하여 한 장의 이미지로 저장할 수 있는 위키형 문서입니다.',infoName:'대표 정보',category:'인물 · 창작 · 설정',source:'개인 아카이브',tags:'#위키 #기록 #아카이브',sectionOneTitle:'개요',sectionOneBody:'문서의 첫 번째 본문입니다. 인물이나 작품, 세계관에 대한 핵심 설명을 자유롭게 작성하세요.\nShift + Enter로 문단을 나눌 수 있습니다.',caption:'이미지에 대한 설명을 입력하세요.',sectionTwoTitle:'상세',sectionTwoBody:'두 번째 본문에는 세부 설정, 관계, 타임라인이나 감상 등을 정리할 수 있습니다.'};
var defaults={accent:'#00a495',paper:'#ffffff',brand:'',title:'',subtitle:'',summary:'',infoName:'',category:'',source:'',tags:'',sectionOneTitle:'',sectionOneBody:'',caption:'',sectionTwoTitle:'',sectionTwoBody:'',profileImage:'',bodyImage:'',profileCrop:{zoom:100,x:50,y:50},bodyCrop:{zoom:100,x:50,y:50}};
var state;try{state=Object.assign(JSON.parse(JSON.stringify(defaults)),JSON.parse(localStorage.getItem('wiki-frame-v1')||'{}'))}catch(error){state=JSON.parse(JSON.stringify(defaults))}
state.profileCrop=Object.assign({zoom:100,x:50,y:50},state.profileCrop||{});state.bodyCrop=Object.assign({zoom:100,x:50,y:50},state.bodyCrop||{});
var exporting=false,activeImage=null,sheet=document.getElementById('wikiSheet'),frame=document.querySelector('.sheet-frame');
var textKeys=['brand','title','subtitle','summary','infoName','category','source','tags','sectionOneTitle','sectionOneBody','caption','sectionTwoTitle','sectionTwoBody'];
var inputMap={brand:'brandInput',title:'titleInput',subtitle:'subtitleInput',summary:'summaryInput',infoName:'infoNameInput',category:'categoryInput',source:'sourceInput',tags:'tagsInput',sectionOneTitle:'sectionOneTitleInput',sectionOneBody:'sectionOneBodyInput',caption:'captionInput',sectionTwoTitle:'sectionTwoTitleInput',sectionTwoBody:'sectionTwoBodyInput'};
var viewMap={title:'titleView',subtitle:'subtitleView',summary:'summaryView',infoName:'infoNameView',category:'categoryView',source:'sourceView',tags:'tagsView',sectionOneTitle:'sectionOneTitleView',sectionOneBody:'sectionOneBodyView',caption:'captionView',sectionTwoTitle:'sectionTwoTitleView',sectionTwoBody:'sectionTwoBodyView'};
function valueOf(key){var value=String(state[key]||'');return value.trim()?value:(exporting?'':examples[key]||'')}
function save(){try{localStorage.setItem('wiki-frame-v1',JSON.stringify(state))}catch(error){}}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function fitFrame(){requestAnimationFrame(function(){frame.style.height=Math.ceil(sheet.getBoundingClientRect().height)+'px'})}
function fitLine(field){if(!field||!field.classList.contains('line'))return;field.style.height='auto';field.style.height=Math.max(37,field.scrollHeight)+'px'}
function imageFile(input,done){var file=input.files&&input.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){done(String(reader.result))};reader.readAsDataURL(file)}
function imageData(slot){if(slot==='profile')return state.profileImage?{slot:'profile',source:state.profileImage,crop:state.profileCrop,box:document.querySelector('[data-image-slot="profile"]'),label:'대표 이미지'}:null;return state.bodyImage?{slot:'body',source:state.bodyImage,crop:state.bodyCrop,box:document.querySelector('[data-image-slot="body"]'),label:'본문 이미지'}:null}
function layoutImage(image,crop){if(!image||!image.naturalWidth)return;var box=image.parentElement,bw=box.clientWidth,bh=box.clientHeight,x=Number(crop.x),y=Number(crop.y),zoom=Math.max(1,Number(crop.zoom||100)/100);if(!Number.isFinite(x))x=50;if(!Number.isFinite(y))y=50;var cover=Math.max(bw/image.naturalWidth,bh/image.naturalHeight),width=image.naturalWidth*cover*zoom,height=image.naturalHeight*cover*zoom;image.style.width=width+'px';image.style.height=height+'px';image.style.left=(-(width-bw)*clamp(x,0,100)/100)+'px';image.style.top=(-(height-bh)*clamp(y,0,100)/100)+'px'}
function mountImage(data){if(!data)return;var image=document.createElement('img');image.className='native-image';image.alt='';image.src=data.source;image._cropData=data.crop;data.box.querySelector('span').style.display='none';data.box.appendChild(image);if(image.complete)layoutImage(image,data.crop);else image.onload=function(){layoutImage(image,data.crop);fitFrame()};setupImage(data,image)}
function setupImage(data,image){image.tabIndex=0;image.setAttribute('role','button');image.setAttribute('aria-label',data.label+' 위치 조정');image.onpointerdown=function(event){if(event.button!==0)return;event.preventDefault();selectImage(data.slot);var rect=data.box.getBoundingClientRect(),startX=event.clientX,startY=event.clientY,start={x:Number(data.crop.x),y:Number(data.crop.y)};image.setPointerCapture&&image.setPointerCapture(event.pointerId);function move(e){data.crop.x=clamp(start.x-(e.clientX-startX)/rect.width*100,0,100);data.crop.y=clamp(start.y-(e.clientY-startY)/rect.height*100,0,100);layoutImage(image,data.crop)}function stop(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);save()}window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)};image.onwheel=function(event){event.preventDefault();selectImage(data.slot);data.crop.zoom=clamp(Number(data.crop.zoom)+(event.deltaY<0?5:-5),100,250);layoutImage(image,data.crop);save()};image.onclick=function(){selectImage(data.slot)}}
function selectImage(slot){document.querySelectorAll('.active-image').forEach(function(el){el.classList.remove('active-image')});var data=imageData(slot);if(!data)return;activeImage=slot;var image=data.box.querySelector('img');image.classList.add('active-image');document.getElementById('imageStatus').textContent=data.label+' 선택됨 · '+data.crop.zoom+'% · 드래그 이동 · 휠 확대/축소 · 방향키 미세조정'}
function render(){sheet.style.setProperty('--accent',state.accent);sheet.style.setProperty('--paper',state.paper);document.querySelectorAll('[data-brand]').forEach(function(el){el.textContent=valueOf('brand')});Object.keys(viewMap).forEach(function(key){document.getElementById(viewMap[key]).textContent=valueOf(key)});document.getElementById('tocOne').textContent=valueOf('sectionOneTitle');document.getElementById('tocTwo').textContent=valueOf('sectionTwoTitle');document.getElementById('leadText').textContent=valueOf('summary');document.querySelectorAll('.image-slot img').forEach(function(image){image.remove()});document.querySelectorAll('.image-slot>span').forEach(function(span){span.style.display='grid'});mountImage(imageData('profile'));mountImage(imageData('body'));fitFrame()}
textKeys.forEach(function(key){var field=document.getElementById(inputMap[key]);field.value=state[key];field.placeholder=examples[key]||'';fitLine(field);field.oninput=function(){state[key]=field.value;fitLine(field);save();render()}});document.getElementById('accentInput').value=state.accent;document.getElementById('paperInput').value=state.paper;document.getElementById('accentInput').oninput=function(){state.accent=this.value;save();render()};document.getElementById('paperInput').oninput=function(){state.paper=this.value;save();render()};
document.getElementById('profileUpload').onchange=function(){imageFile(this,function(value){state.profileImage=value;save();render();selectImage('profile')})};document.getElementById('bodyUpload').onchange=function(){imageFile(this,function(value){state.bodyImage=value;save();render();selectImage('body')})};
document.addEventListener('keydown',function(event){if(event.key==='Enter'&&event.shiftKey&&event.target.tagName==='TEXTAREA'){event.preventDefault();event.target.setRangeText('\n',event.target.selectionStart,event.target.selectionEnd,'end');event.target.dispatchEvent(new Event('input',{bubbles:true}));return}if(!activeImage||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)||event.target.closest('input,textarea,button'))return;var data=imageData(activeImage),step=event.shiftKey?5:1;if(!data)return;event.preventDefault();if(event.key==='ArrowLeft')data.crop.x=clamp(data.crop.x+step,0,100);if(event.key==='ArrowRight')data.crop.x=clamp(data.crop.x-step,0,100);if(event.key==='ArrowUp')data.crop.y=clamp(data.crop.y+step,0,100);if(event.key==='ArrowDown')data.crop.y=clamp(data.crop.y-step,0,100);layoutImage(data.box.querySelector('img'),data.crop);save()});
document.getElementById('resetButton').onclick=function(){if(!confirm('입력한 내용과 이미지를 모두 초기화할까요?'))return;localStorage.removeItem('wiki-frame-v1');state=JSON.parse(JSON.stringify(defaults));textKeys.forEach(function(key){document.getElementById(inputMap[key]).value=''});document.getElementById('accentInput').value=state.accent;document.getElementById('paperInput').value=state.paper;activeImage=null;render()};
document.getElementById('saveButton').onclick=async function(){if(!window.html2canvas)return alert('저장 기능을 불러오는 중입니다.');var button=this;button.disabled=true;button.textContent='저장 중…';exporting=true;document.body.classList.add('saving');render();try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;await Promise.all(Array.from(sheet.querySelectorAll('img.native-image')).map(function(image){return image.decode?image.decode().catch(function(){}):Promise.resolve()}));sheet.querySelectorAll('img.native-image').forEach(function(image){layoutImage(image,image._cropData)});await new Promise(function(resolve){requestAnimationFrame(function(){requestAnimationFrame(resolve)})});var area=sheet.scrollWidth*sheet.scrollHeight,scale=Math.max(2,Math.min(4,Math.sqrt(45000000/Math.max(1,area)))),canvas=await window.html2canvas(sheet,{scale:scale,backgroundColor:state.paper,useCORS:true,logging:false,imageTimeout:30000}),link=document.createElement('a');link.download='wiki-'+(state.title||'document')+'.png';link.href=canvas.toDataURL('image/png');link.click()}catch(error){alert('PNG를 만들지 못했습니다. 이미지 용량을 줄여 다시 시도해주세요.')}finally{exporting=false;document.body.classList.remove('saving');button.disabled=false;button.textContent='PNG 저장';render()}};
var panel=document.getElementById('editorPanel'),toggle=document.getElementById('mobileToggle'),closeButton=document.getElementById('mobileClose'),backdrop=document.getElementById('editorBackdrop');function setEditor(open){document.body.classList.toggle('editor-open',open);panel.classList.toggle('open',open);backdrop.classList.toggle('show',open);toggle.setAttribute('aria-expanded',String(open))}toggle.onclick=function(){setEditor(true)};closeButton.onclick=function(){setEditor(false)};backdrop.onclick=function(){setEditor(false)};window.addEventListener('resize',fitFrame);render();
